version: "3.8"

services:
  next_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tranvansi6302/bysharing:ai-beauty-v3
    container_name: next-app
    restart: always
    ports:
      - "3000:3000"

  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx-proxy
  #   restart: always
  #   ports:
  #     - "26000:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - next_app
